### ISSUE TITLE
When closing server, all clients are disconnected with id 0

### ISSUE THREAD

**Issue by hussainabidi1** [thethreediepeteers/diatom-server#1]
When the server is closed, all clients are disconnected with the message "Client 0 disconnected" instead of their respective ids.

**Comment by ClashTest311** [comment]
Not true for me
![Screenshot from 2024-09-12 12-57-59](https://github.com/user-attachments/assets/7ce322b1-a535-462e-b88a-63fcc1c7a8d1)
